version: '2'

services:

  bundler:
    ports: [ '3000:4337' ]
    image: stackupwallet/stackup-bundler
    environment:
      - ERC4337_BUNDLER_ETH_CLIENT_URL=http://geth-dev:8545
      - ERC4337_BUNDLER_PRIVATE_KEY=c6cbc5ffad570fdad0544d1b5358a36edeb98d163b6567912ac4754e144d4edb
      - ERC4337_BUNDLER_DEBUG_MODE=true
    depends_on:
      fund-signer:
        condition: service_completed_successfully

  fund-signer:
    image: ethereum/client-go:release-1.10
    entrypoint: 'geth --exec "eth.sendTransaction({from: eth.accounts[0], to: \"0x43378ff8C70109Ee4Dbe85aF34428ab0615EBd23\", value: web3.toWei(10000, \"ether\")})" attach http://geth-dev:8545'
    depends_on:
      geth-dev:
        condition: service_started

  geth-dev:
    build: ../aabundler/geth-dev
    ports: [ '8545:8545' ]
