# start a standlone bundler for testing.
# bring up a the bundler with its own geth instance

services:

  bundler:
    ports: [ "3001:3000" ]
    image: sherifahmed990/voltaire-bundler-p2p:a01
    command: --entrypoints ${ENTRYPOINT}
        --bundler_secret 0xc6cbc5ffad570fdad0544d1b5358a36edeb98d163b6567912ac4754e144d4edb
        --chain_id 1337
        --rpc_url 0.0.0.0
        --verbose
        --debug
        --bundle_interval 0 
        --ethereum_node_url $ETH_RPC_URL
        --p2p_enr_address $BUNDLER2_IP
        --p2p_enr_tcp_port 9000
        --p2p_enr_udp_port 9000
        --p2p_boot_nodes_enr $BOOT_ENR
    networks:
      default:
      p2p:
        ipv4_address: $BUNDLER2_IP

