services:
  bundler:
    image: ghcr.io/candidelabs/voltaire/voltaire-bundler:latest
    ports: [ '3000:3000' ]
    command: >
      --bundler_secret 0xc6cbc5ffad570fdad0544d1b5358a36edeb98d163b6567912ac4754e144d4edb
      --rpc_url 0.0.0.0
      --ethereum_node_url $ETH_RPC_URL
      --chain_id 1337
      --verbose
      --debug
      --disable_p2p
      --disable_v6
