services:

  bundler:
    ports: [ '3000:3000' ]
    image: ghcr.io/pimlicolabs/alto:latest
    command:
      - --network-name=local
    environment:
      - ALTO_ENTRY_POINT=$ENTRYPOINT
      - ALTO_MAX_SIGNERS=1
      - ALTO_RPC_URL=$ETH_RPC_URL
      - ALTO_SIGNER_PRIVATE_KEYS=0xc6cbc5ffad570fdad0544d1b5358a36edeb98d163b6567912ac4754e144d4edb
      - ALTO_UTILITY_PRIVATE_KEY=0xc6cbc5ffad570fdad0544d1b5358a36edeb98d163b6567912ac4754e144d4edb
      - ALTO_MIN_BALANCE=0
