services:
  bundler:
    image: ghcr.io/pimlicolabs/alto:v1.2.4
    ports: [ "3000:3000" ]
    environment:
      - ALTO_ENTRYPOINTS=$ENTRYPOINT
      - ALTO_MAX_SIGNERS=1
      - ALTO_EXECUTOR_PRIVATE_KEYS=0xc6cbc5ffad570fdad0544d1b5358a36edeb98d163b6567912ac4754e144d4edb
      - ALTO_UTILITY_PRIVATE_KEY=0xc6cbc5ffad570fdad0544d1b5358a36edeb98d163b6567912ac4754e144d4edb
      - ALTO_MIN_BALANCE=0
      - ALTO_BUNDLE_MODE=manual
      - ALTO_SAFE_MODE=true
      - ALTO_ENVIRONMENT=development
      - ALTO_ENABLE_DEBUG_ENDPOINTS=true
      - ALTO_DEPLOY_SIMULATIONS_CONTRACT=true
      - ALTO_MAX_BLOCK_RANGE=5000
      - ALTO_RPC_URL=$ETH_RPC_URL
