# start a standlone bundler for testing.
# bring up a the bundler with its own geth instance

services:

  bundler:
    ports: [ "3001:3000" ]
    image: etherspot/skandha
    command: node --testingMode --api.port 3000
      --redirectRpc --executor.bundlingMode manual 
      --p2p.enrHost 172.30.0.4
      --p2p.bootEnrs $ENR
    environment:
      - SKANDHA_DEV_RPC=$ETH_RPC_URL
      - SKANDHA_DEV_ENTRYPOINTS=${ENTRYPOINT}
      - SKANDHA_DEV_RELAYER=junk junk junk junk junk junk junk junk junk junk junk test
      - SKANDHA_DEV_BENEFICIARY=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
