# start a standlone bundler for testing.
# bring up a the bundler with its own geth instance

services:

  bundler:
    ports: [ '3000:3000' ]
    image: etherspot/skandha
    command: start --testingMode --api.port 3000
    volumes:
      - ./config.json:/usr/app/config.json
    environment:
      - BENCHMARK=true

