# start a standlone bundler for testing.
# bring up a the bundler with its own geth instance

services:

  bundler:
    ports: [ '3000:3000' ]
    image: etherspot/skandha
    command: standalone --testingMode --api.port 3000
    environment:
      - SKANDHA_DEV_RPC=$ETH_RPC_URL
      - SKANDHA_DEV_ENTRYPOINTS=${ENTRYPOINT}
      - SKANDHA_DEV_RELAYER=test test test test test test test test test test test junk
      - SKANDHA_DEV_BENEFICIARY=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
