services:
  bundler:
    image: transeptorlabs/bundler:latest
    ports: [ '3000:3000' ]
    environment:
      - TRANSEPTOR_MNEMONIC=test test test test test test test test test test test junk
      - TRANSEPTOR_ENTRYPOINT_ADDRESS=$ENTRYPOINT
      - TRANSEPTOR_BENEFICIARY=0xd21934eD8eAf27a67f0A70042Af50A1D6d195E81
    command: >
      --network $ETH_RPC_URL
      --port 3000
      --txMode base
      --httpApi web3,eth,debug