services:

  bundler:
    ports: [ "3000:3000" ]
    image: ghcr.io/silius-rs/silius:latest
    command: bundler
      --eth-client-address $ETH_RPC_URL
      --datadir data/silius
      --mnemonic-file /root/${BUNDLER_ACCOUNT}
      --beneficiary ${BUNDLER_ACCOUNT}
      --entry-points $ENTRYPOINT
      --http --http.addr 0.0.0.0
      --http.port 3000
      --http.api eth,debug,web3
      --enable-p2p
      --p2p.addr $BUNDLER_IP
      --p2p.baddr $BUNDLER_IP
    volumes:
      - ./keys:/root
      - ./discovery-secret:/data/silius/discovery-secret
    networks:
      default:
      p2p:
        ipv4_address: $BUNDLER_IP


