# start a standlone bundler for testing.
# bring up a the bundler with its own geth instance

version: '2'

services:

  bundler:
    ports: [ '3000:3000' ]
    image: sherifahmed990/voltaire-bundler:0.19
    command: --entrypoint 0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789 --bundler_secret 0xc6cbc5ffad570fdad0544d1b5358a36edeb98d163b6567912ac4754e144d4edb --rpc_url 0.0.0.0 --ethereum_node_url http://geth-dev:8545 --chain_id 1337 --bundle_interval 0 --verbose --debug

  fund-signer:
    image: ethereum/client-go:release-1.10
    entrypoint: 'geth --exec "eth.sendTransaction({from: eth.accounts[0], to: \"0x43378ff8C70109Ee4Dbe85aF34428ab0615EBd23\", value: web3.toWei(10000, \"ether\")})" attach http://geth-dev:8545'
    depends_on:
      geth-dev:
        condition: service_started
        
  geth-dev:
    build: geth-dev
    ports: [ '8545:8545' ]
